[SALES-PER-CHANNEL-TOTAL]
title       = "sales"
category    = "sales"
feature     = "BASIC"
with_totals = true
query       = """
SELECT sale_sourceSystem_code            as "channel",
       SUM(qty)                          as "count",
       SUM(sale_price_total_ExVat) / 100 as "total price"
FROM inventory_out
WHERE mutationType = 'sale'
AND (inventory_out.onDay >= @date_from_incl AND inventory_out.onDay <= @date_to_incl)
GROUP BY sale_sourceSystem_code
ORDER by SUM(sale_price_total_ExVat) DESC
"""

    [SALES-PER-CHANNEL-TOTAL.parameters.periode]
    type = "DATE_RANGE"
    from = "@date_from_incl"
    to = "@date_to_incl"
    field_type = "DT"
    params = ["testing one", "testing two"]
#    default = "TODAY"

    [SALES-PER-CHANNEL-TOTAL.parameters.tag]
    display_name  = "Tag filter"
    name          = "@tagId"
    type          = "FILTER_LOOKUP"
    field_type    = "u8"
    list_provider = "Ruzzie.SimpleReports.Db.SqlListProvider"
    params        = ["SELECT tagId, name from tag;"]

    [SALES-PER-CHANNEL-TOTAL.parameters.uint64test]
    display_name  = "filter test"
    name          = "@uint64"
    type          = "FILTER_LOOKUP"
    field_type    = "u64"
    list_provider = "Ruzzie.SimpleReports.Db.SqlListProvider"
    params        = ["SELECT tagId, tagId from tag;"]


    [SALES-PER-CHANNEL-TOTAL.parameters.int64test]
    display_name  = "filter test"
    name          = "@int64"
    type          = "FILTER_LOOKUP"
    field_type    = "i64"
    list_provider = "Ruzzie.SimpleReports.Db.SqlListProvider"
    params        = ["SELECT tagId, tagId from tag;"]

    [SALES-PER-CHANNEL-TOTAL.parameters.strtest]
    display_name  = "filter test"
    name          = "@s"
    type          = "FILTER_LOOKUP"
    field_type    = "s"
    list_provider = "Ruzzie.SimpleReports.Db.SqlListProvider"
    params        = ["SELECT tag, tag from tag;"]

    [SALES-PER-CHANNEL-TOTAL.parameters.timezone]
    display_name  = "Timezone"
    name          = "@tz"
    type          = "TIMEZONE"
    field_type    = "S"
    list_provider = "Ruzzie.SimpleReports.Db.SqlListProvider"
    params        = ["select name, name from pg_timezone_names where (pg_timezone_names.name NOT LIKE 'posix%');"]

    [SALES-PER-CHANNEL-TOTAL.parameters.interval]
    display_name  = "Interval"
    name          = "@interval"
    type          = "TIME_INTERVAL"
    #values        = [{ key = "1 day"   , value = "1 day"   },
    #                 { key = "1 week"  , value = "1 week"  },
    #                 { key = "4 weeks" , value = "4 weeks" },
    #                 { key = "13 weeks", value = "13 weeks"},
    #                 { key = "30 days" , value = "30 days" },
    #                 { key = "1 year"  , value = "365 days"}]
    field_type    = "S"  # 1 day, 2 days, 1 week, 2 weeks, 1 hour etc... (month and year are not supported yet, 365 days is, or 31 days, or 4 weeks etc)

